language: ruby
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
script: bundle exec rspec spec
cache: bundler
rvm:
  - 2.2
  - 2.3.4
  - 2.4.1
  - jruby-9.1.10.0
